#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

use App\Application as BaseApplication;

$app = new BaseApplication;

require_once __DIR__ . '/config/config.php';
require_once __DIR__ . '/config/providers.php';
require_once __DIR__ . '/config/routes.php';

$application = new Application();

$helperSet = new \Symfony\Component\Console\Helper\HelperSet(array(
    'db' => new \Doctrine\DBAL\Tools\Console\Helper\ConnectionHelper($app['db']),
    'connection' => new \Doctrine\DBAL\Tools\Console\Helper\ConnectionHelper($app['db']),
    'dialog' => new \Symfony\Component\Console\Helper\QuestionHelper(),
));

$application->setHelperSet($helperSet);

$application->addCommands(array(
    // ...

    // Migrations Commands
    new \Doctrine\DBAL\Migrations\Tools\Console\Command\ExecuteCommand(),
    new \Doctrine\DBAL\Migrations\Tools\Console\Command\GenerateCommand(),
    new \Doctrine\DBAL\Migrations\Tools\Console\Command\MigrateCommand(),
    new \Doctrine\DBAL\Migrations\Tools\Console\Command\StatusCommand(),
    new \Doctrine\DBAL\Migrations\Tools\Console\Command\VersionCommand(),

    // DBAL Commands
    new \Doctrine\DBAL\Tools\Console\Command\RunSqlCommand(),
    new \Doctrine\DBAL\Tools\Console\Command\ImportCommand(),
));

exit($application->run());